# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gttg',
            options={'verbose_name': 'dfsfd'},
        ),
        migrations.AddField(
            model_name='gttg',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 6, 17, 8, 7, 7, 140882, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
