# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160621_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gttg',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
